name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on the push to the 'main' branch
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build --build-arg PAT_GITHUB=${{ secrets.PAT_GITHUB }} -t ghcr.io/nagarro-devops-coe/cloud-cost-optimizer:latest .
      # Push the Docker image
      - name: Push Docker image
        run: |
          docker push ghcr.io/nagarro-devops-coe/cloud-cost-optimizer:latest
